language: java
dist: trusty

jdk:
  - openjdk14

services:
  - docker

#before_install:
#  - chmod +x mvnw

before_script:
  - docker-compose -f docker/dev/docker-compose.yml up -d

jobs:
  include:
    - stage: testAll
      script: mvn test
    - stage: sonar
      script: mvn verify sonar:sonar


after_script:
  - docker-compose -f docker/dev/docker-compose.yml stop
  - docker-compose -f docker/dev/docker-compose.yml rm -fyml down