version: "3.7"

services:
  config:
    container_name: config-server
    image: org.ocr/config-server:1.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:9093:9093"

  eureka:
    container_name: eureka-server
    image: org.ocr/eureka-server:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
    ports:
      - "127.0.0.1:9094:9094"

  zuul:
    container_name: zuul-server
    image: org.ocr/zuul-server:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "eureka"
    ports:
      - "127.0.0.1:9095:9095"

  postgres:
    container_name: postgres
    image: postgres:12.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: loan
      POSTGRES_PASSWORD: 0
      POSTGRES_DB: usr
    volumes:
      - "./docker/dev/init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
#      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  batch:
    container_name: microservice-batch
    image: org.ocr/microservice-batch:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "zuul"
      - "user"
      - "document"
      - "loan"
      - "eureka"
      - "postgres"
      - "reservation"
    ports:
      - "127.0.0.1:9097:9097"

  document:
    container_name: microservice-document
    image: org.ocr/microservice-document:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "eureka"
      - "zuul"
      - "postgres"
    ports:
      - "127.0.0.1:9091:9091"

  fileserver:
    container_name: microservice-fileserver
    image: org.ocr/microservice-fileserver:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "zuul"
      - "eureka"
    ports:
      - "127.0.0.1:9092:9092"

  loan:
    container_name: microservice-loan
    image: org.ocr/microservice-loan:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "zuul"
      - "eureka"
      - "postgres"
    ports:
      - "127.0.0.1:9090:9090"

  reservation:
    container_name: microservice-reservation
    image: org.ocr/microservice-reservation:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "eureka"
      - "postgres"
      - "zuul"
    ports:
      - "127.0.0.1:9100:9100"

  user:
    container_name: microservice-user
    image: org.ocr/microservice-user:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "postgres"
      - "eureka"
      - "zuul"
    ports:
      - "127.0.0.1:9096:9096"

  client:
    container_name: client
    image: org.ocr/client:1.0
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:9094/eureka
        -DCONFIG_SERVER=http://config:9093
    depends_on:
      - "config"
      - "eureka"
      - "document"
      - "fileserver"
      - "loan"
      - "reservation"
      - "zuul"
      - "user"
    ports:
      - "127.0.0.1:9099:9099"